random_seed: 42
model:
  name: "Rostlab/prot_bert_bfd"
  frozen_layers: 27
training:
  max_epochs: 50
  learning_rate: 0.0001
  weight_decay: 0.0001
  adam_epsilon: 0.00000001
  warmup_steps: 5
  gpus: 1
  precision: 16
  amp_backend: "apex"
  amp_level: "O1"
  fast_dev: False
  training_batches_per_epoch: 5000
  val_batches_per_epoch: 1000
tracking:
  experiment_name: "ProteinClassification"
  checkpoints_folder: "./models"
data:
  db_path: "/home/ilyabushmakin/Documents/Projects/DataStorage/transporters_clf/sequences.lmdb"
  batch_size: 3
  val_cogs:
    - KOG3944
    - KOG1053
    - COG1291
    - KOG0255
    - COG0765
    - arCOG00194
  test_cogs:
    - KOG1893
    - KOG1054
    - COG3781
    - KOG0254
    - COG0841
    - arCOG00130
